package com.example.ipvcconnect

object EmpresasData {
    val todasEmpresas = listOf(
        // Empresas de Engenharia Informática
        Empresa(
            nome = "Critical Software",
            descricao = "Desenvolvimento de software crítico",
            localizacao = "Braga",
            curso = "Engenharia Informática",
            morada = "Rua Padre António Vieira 38, 4715-293 Braga",
            telefone = "253123456",
            email = "contact@critical.pt",
            site = "https://www.criticalsoftware.com",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.5454,
            longitude = -8.4265
        ),
        Empresa(
            nome = "Primavera BSS",
            descricao = "Software de gestão empresarial",
            localizacao = "Braga",
            curso = "Engenharia Informática",
            morada = "Rua D. João I 90, 4715-293 Braga",
            telefone = "253987654",
            email = "contact@primavera.pt",
            site = "https://www.primaverabss.com",
            vagasDisponiveis = 5,
            vagasOcupadas = 1,
            latitude = 41.5517,
            longitude = -8.4229
        ),
        // Empresas de Enfermagem
        Empresa(
            nome = "Hospital de Viana",
            descricao = "Hospital público",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem",
            morada = "Estrada de Santa Luzia, 4901-858 Viana do Castelo",
            telefone = "258802100",
            email = "recursos.humanos@ulsam.min-saude.pt",
            site = "https://www.ulsam.min-saude.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 2,
            latitude = 41.7019,
            longitude = -8.8344
        ),
        Empresa(
            nome = "Hospital CUF Porto",
            descricao = "Hospital privado",
            localizacao = "Porto",
            curso = "Enfermagem",
            morada = "Estrada da Circunvalação 14341, 4100-180 Porto",
            telefone = "220039000",
            email = "careers@cuf.pt",
            site = "https://www.cuf.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 3,
            latitude = 41.1812,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Hospital de Braga",
            descricao = "Hospital público",
            localizacao = "Braga",
            curso = "Enfermagem",
            morada = "Sete Fontes, 4710-243 Braga",
            telefone = "253027000",
            email = "recursos.humanos@hb.min-saude.pt",
            site = "https://www.hospitaldebraga.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 1,
            latitude = 41.5647,
            longitude = -8.4018
        ),
        Empresa(
            nome = "Hospital Lusíadas Porto",
            descricao = "Hospital privado",
            localizacao = "Porto",
            curso = "Enfermagem",
            morada = "Rua Calouste Gulbenkian 171, 4050-145 Porto",
            telefone = "220911000",
            email = "careers@lusiadas.pt",
            site = "https://www.lusiadas.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 4,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Hospital da Luz Viana",
            descricao = "Hospital privado",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem",
            morada = "Rua Conde de Aurora 50, 4900-430 Viana do Castelo",
            telefone = "258009000",
            email = "careers@hospitaldaluz.pt",
            site = "https://www.hospitaldaluz.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Centro de Saúde de Ponte de Lima",
            descricao = "Centro de saúde público",
            localizacao = "Ponte de Lima",
            curso = "Enfermagem",
            morada = "Rua Conde de Bertiandos, 4990-078 Ponte de Lima",
            telefone = "258909280",
            email = "geral@csplima.min-saude.pt",
            site = "www.csplima.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 1,
            latitude = 41.7667,
            longitude = -8.5833
        ),
        Empresa(
            nome = "USF Atlântico Norte",
            descricao = "Unidade de saúde familiar",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem",
            morada = "Rua da Bandeira 567, 4900-501 Viana do Castelo",
            telefone = "258806860",
            email = "usf.atlantico@arsnorte.min-saude.pt",
            site = "www.usf.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Centro de Saúde de Barcelos",
            descricao = "Centro de saúde público",
            localizacao = "Barcelos",
            curso = "Enfermagem",
            morada = "Campo da República, 4750-275 Barcelos",
            telefone = "253808300",
            email = "geral@csb.min-saude.pt",
            site = "www.csb.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.5389,
            longitude = -8.6155
        ),
        Empresa(
            nome = "Centro de Saúde de Viana do Castelo",
            descricao = "Cuidados de saúde primários",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem",
            morada = "Rua da Bandeira 567, 4900-501 Viana do Castelo",
            telefone = "258802310",
            email = "cs.viana@arsnorte.min-saude.pt",
            site = "www.cs.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Santa Casa da Misericórdia de Ponte de Lima",
            descricao = "Instituição de saúde",
            localizacao = "Ponte de Lima",
            curso = "Enfermagem",
            morada = "Rua General Norton de Matos, 4990-118 Ponte de Lima",
            telefone = "258909100",
            email = "geral@scmplima.pt",
            site = "www.scmplima.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.7667,
            longitude = -8.5833
        ),
        Empresa(
            nome = "Clínica Médica de Viana",
            descricao = "Clínica privada",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem",
            morada = "Rua Nova de Santana 145, 4900-540 Viana do Castelo",
            telefone = "258822456",
            email = "geral@clinicaviana.pt",
            site = "www.clinicaviana.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        // Engenharia Civil e do Ambiente
        Empresa(
            nome = "Mota-Engil",
            descricao = "Construção civil e obras públicas",
            localizacao = "Porto",
            curso = "Engenharia Civil e do Ambiente",
            morada = "Rua do Rego Lameiro 38, 4300-454 Porto",
            telefone = "225190300",
            email = "careers@mota-engil.pt",
            site = "https://www.mota-engil.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1494,
            longitude = -8.5913
        ),
        Empresa(
            nome = "Teixeira Duarte",
            descricao = "Construção e engenharia",
            localizacao = "Porto",
            curso = "Engenharia Civil e do Ambiente",
            morada = "Av. da Boavista 1588, 4100-115 Porto",
            telefone = "226166570",
            email = "rh@teixeiraduarte.pt",
            site = "https://www.teixeiraduarte.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "DST Group",
            descricao = "Construção e ambiente",
            localizacao = "Braga",
            curso = "Engenharia Civil e do Ambiente",
            morada = "Rua de Pitancinhos, 4700-727 Braga",
            telefone = "253307200",
            email = "careers@dstsgps.com",
            site = "https://www.dstsgroup.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.5454,
            longitude = -8.4265
        ),
        Empresa(
            nome = "Casais",
            descricao = "Construção civil",
            localizacao = "Braga",
            curso = "Engenharia Civil e do Ambiente",
            morada = "Rua do Anjo 27, 4700-305 Braga",
            telefone = "253605140",
            email = "rh@casais.pt",
            site = "https://www.casais.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.5503,
            longitude = -8.4289
        ),
        Empresa(
            nome = "Somague",
            descricao = "Engenharia e construção",
            localizacao = "Porto",
            curso = "Engenharia Civil e do Ambiente",
            morada = "Rua da Constituição 657, 4200-201 Porto",
            telefone = "225574700",
            email = "careers@somague.pt",
            site = "https://www.somague.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Engenharia Mecânica
        Empresa(
            nome = "Salvador Caetano",
            descricao = "Indústria automóvel",
            localizacao = "Vila Nova de Gaia",
            curso = "Engenharia Mecânica",
            morada = "Av. Vasco da Gama 1410, 4431-956 Vila Nova de Gaia",
            telefone = "227867000",
            email = "rh@salvadorcaetano.pt",
            site = "https://www.salvadorcaetano.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1333,
            longitude = -8.6167
        ),
        Empresa(
            nome = "Continental Mabor",
            descricao = "Indústria de pneus",
            localizacao = "Vila Nova de Famalicão",
            curso = "Engenharia Mecânica",
            morada = "Rua Adelino Leitão 330, 4760-652 Lousado",
            telefone = "252499100",
            email = "careers@conti.de",
            site = "https://www.conti.de",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.3500,
            longitude = -8.5333
        ),
        Empresa(
            nome = "Efacec",
            descricao = "Energia e transportes",
            localizacao = "Matosinhos",
            curso = "Engenharia Mecânica",
            morada = "Via Eng Belmiro Mendes de Azevedo, 4470-605 Matosinhos",
            telefone = "229403100",
            email = "hr@efacec.com",
            site = "https://www.efacec.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.2000,
            longitude = -8.6833
        ),
        Empresa(
            nome = "Volkswagen Autoeuropa",
            descricao = "Indústria automóvel",
            localizacao = "Palmela",
            curso = "Engenharia Mecânica",
            morada = "Quinta da Marquesa, 2954-024 Palmela",
            telefone = "212123000",
            email = "recursos.humanos@volkswagen.pt",
            site = "https://www.volkswagen.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 38.5833,
            longitude = -8.9000
        ),
        Empresa(
            nome = "Bosch Car Multimedia",
            descricao = "Sistemas automotivos",
            localizacao = "Braga",
            curso = "Engenharia Mecânica",
            morada = "Rua Max Grundig 35, 4705-820 Braga",
            telefone = "253606100",
            email = "careers.braga@bosch.com",
            site = "https://www.bosch.com",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.5612,
            longitude = -8.4321
        ),
        // Arte e Design
        Empresa(
            nome = "Fundação de Serralves",
            descricao = "Museu de arte contemporânea",
            localizacao = "Porto",
            curso = "Arte e Design",
            morada = "Rua D. João de Castro 210, 4150-417 Porto",
            telefone = "226156500",
            email = "recursos.humanos@serralves.pt",
            site = "https://www.serralves.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Casa da Música",
            descricao = "Centro cultural e musical",
            localizacao = "Porto",
            curso = "Arte e Design",
            morada = "Av. da Boavista 604-610, 4149-071 Porto",
            telefone = "220120220",
            email = "rh@casadamusica.com",
            site = "https://www.casadamusica.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Educação Básica
        Empresa(
            nome = "Escola Básica António Feijó",
            descricao = "Escola pública de ensino básico",
            localizacao = "Ponte de Lima",
            curso = "Educação Básica",
            morada = "Rua Agostinho José Taveira, 4990-072 Ponte de Lima",
            telefone = "258909070",
            email = "secretaria@aeaf.edu.pt",
            site = "https://www.aeaf.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.7667,
            longitude = -8.5833
        ),
        Empresa(
            nome = "Colégio do Minho",
            descricao = "Escola privada",
            localizacao = "Viana do Castelo",
            curso = "Educação Básica",
            morada = "Av. dos Combatentes, 4900-563 Viana do Castelo",
            telefone = "258800010",
            email = "geral@colegiominho.pt",
            site = "https://www.colegiominho.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Centro Escolar da Meadela",
            descricao = "Escola básica pública",
            localizacao = "Viana do Castelo",
            curso = "Educação Básica",
            morada = "Rua da Veiga, 4900-343 Viana do Castelo",
            telefone = "258839160",
            email = "ce.meadela@gmail.com",
            site = "https://www.cemeadela.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.7019,
            longitude = -8.8344
        ),
        Empresa(
            nome = "Agrupamento de Escolas da Abelheira",
            descricao = "Agrupamento escolar público",
            localizacao = "Viana do Castelo",
            curso = "Educação Básica",
            morada = "Rua José Augusto Vieira, 4900-444 Viana do Castelo",
            telefone = "258809770",
            email = "secretaria@aeabelheira.edu.pt",
            site = "https://www.aeabelheira.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Escola Básica Frei Bartolomeu dos Mártires",
            descricao = "Escola básica pública",
            localizacao = "Viana do Castelo",
            curso = "Educação Básica",
            morada = "Rua Martim Velho, 4900-452 Viana do Castelo",
            telefone = "258800020",
            email = "direcao@aefbm.edu.pt",
            site = "https://www.aefbm.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        // Educação Social Gerontológica
        Empresa(
            nome = "Santa Casa da Misericórdia de Viana",
            descricao = "Instituição de solidariedade social",
            localizacao = "Viana do Castelo",
            curso = "Educação Social Gerontológica",
            morada = "Rua da Bandeira 54, 4900-514 Viana do Castelo",
            telefone = "258822177",
            email = "geral@scmviana.pt",
            site = "https://www.scmviana.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Centro Social e Paroquial de Vila Nova de Anha",
            descricao = "Centro social e paroquial",
            localizacao = "Viana do Castelo",
            curso = "Educação Social Gerontológica",
            morada = "Rua da Igreja, 4935-347 Vila Nova de Anha",
            telefone = "258322153",
            email = "geral@cspvnanha.pt",
            site = "https://www.cspvnanha.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6500,
            longitude = -8.8000
        ),
        // Contabilidade e Fiscalidade
        Empresa(
            nome = "PwC Portugal",
            descricao = "Auditoria e consultoria fiscal",
            localizacao = "Porto",
            curso = "Contabilidade e Fiscalidade",
            morada = "Avenida da Boavista 3523, 4100-139 Porto",
            telefone = "225433000",
            email = "recrutamento@pwc.com",
            site = "https://www.pwc.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "KPMG Portugal",
            descricao = "Auditoria e consultoria",
            localizacao = "Porto",
            curso = "Contabilidade e Fiscalidade",
            morada = "Edifício Burgo, Avenida da Boavista 1837, 4100-133 Porto",
            telefone = "220102300",
            email = "careers@kpmg.pt",
            site = "https://www.kpmg.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "EY Portugal",
            descricao = "Auditoria e consultoria",
            localizacao = "Porto",
            curso = "Contabilidade e Fiscalidade",
            morada = "Avenida da Boavista 36, 4050-112 Porto",
            telefone = "226079500",
            email = "careers@pt.ey.com",
            site = "https://www.ey.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "BDO Portugal",
            descricao = "Auditoria e consultoria",
            localizacao = "Porto",
            curso = "Contabilidade e Fiscalidade",
            morada = "Rua S. João de Brito 605 E, 4100-455 Porto",
            telefone = "226166140",
            email = "recrutamento@bdo.pt",
            site = "https://www.bdo.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Grant Thornton Portugal",
            descricao = "Auditoria e consultoria",
            localizacao = "Porto",
            curso = "Contabilidade e Fiscalidade",
            morada = "Avenida da Boavista 1361, 4100-130 Porto",
            telefone = "226002700",
            email = "careers@pt.gt.com",
            site = "https://www.gt.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Marketing e Comunicação Empresarial
        Empresa(
            nome = "Havas Portugal",
            descricao = "Agência de publicidade",
            localizacao = "Porto",
            curso = "Marketing e Comunicação Empresarial",
            morada = "Rua José Falcão 151, 4050-317 Porto",
            telefone = "225322000",
            email = "careers@havas.pt",
            site = "https://www.havas.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "BBDO Portugal",
            descricao = "Agência de marketing",
            localizacao = "Porto",
            curso = "Marketing e Comunicação Empresarial",
            morada = "Rua Júlio Dinis 247, 4050-324 Porto",
            telefone = "226079800",
            email = "jobs@bbdo.pt",
            site = "https://www.bbdo.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Agronomia
        Empresa(
            nome = "Syngenta Portugal",
            descricao = "Agricultura e biotecnologia",
            localizacao = "Porto",
            curso = "Agronomia",
            morada = "Av. D. João II, Torre Fernão de Magalhães, 1990-084 Porto",
            telefone = "217943200",
            email = "careers.portugal@syngenta.com",
            site = "https://www.syngenta.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Desporto e Lazer
        Empresa(
            nome = "Sport Club Vianense",
            descricao = "Clube desportivo",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Estádio Dr. José de Matos, 4900-347 Viana do Castelo",
            telefone = "258822497",
            email = "geral@scvianense.pt",
            site = "https://www.scvianense.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Ginásio Solinca",
            descricao = "Centro de fitness",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Estrada da Papanata, 4900-470 Viana do Castelo",
            telefone = "258800300",
            email = "careers@solinca.pt",
            site = "https://www.solinca.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Piscina Municipal",
            descricao = "Centro aquático",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Avenida do Atlântico, 4900-348 Viana do Castelo",
            telefone = "258320330",
            email = "desporto@cm-viana-castelo.pt",
            site = "https://www.piscinamunicipal.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Surf Club Viana",
            descricao = "Escola de surf",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Praia do Cabedelo, 4935-161 Viana do Castelo",
            telefone = "258321456",
            email = "info@surfclubviana.pt",
            site = "https://www.surfclubviana.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.6789,
            longitude = -8.8234
        ),
        Empresa(
            nome = "Academia de Ténis",
            descricao = "Escola de ténis",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Rua Sporting Club, 4900-348 Viana do Castelo",
            telefone = "258789123",
            email = "tennis@viana.pt",
            site = "https://www.academiadetenis.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "CrossFit Viana",
            descricao = "Box de CrossFit",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Zona Industrial, 4900-231 Viana do Castelo",
            telefone = "258789456",
            email = "info@crossfitviana.pt",
            site = "https://www.crossfitviana.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.7052,
            longitude = -8.8520
        ),
        Empresa(
            nome = "Centro de Remo",
            descricao = "Clube de remo",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Marina de Viana, 4900-405 Viana do Castelo",
            telefone = "258825789",
            email = "remo@viana.pt",
            site = "https://www.centroremo.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.6915,
            longitude = -8.8205
        ),
        Empresa(
            nome = "Clube de Vela",
            descricao = "Escola de vela",
            localizacao = "Viana do Castelo",
            curso = "Desporto e Lazer",
            morada = "Porto de Mar, 4900-321 Viana do Castelo",
            telefone = "258823456",
            email = "vela@viana.pt",
            site = "https://www.clubedevela.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6827,
            longitude = -8.8349
        ),
        // Enfermagem Veterinária
        Empresa(
            nome = "Hospital Veterinário de Viana",
            descricao = "Hospital veterinário",
            localizacao = "Viana do Castelo",
            curso = "Enfermagem Veterinária",
            morada = "Rua da Bandeira 168, 4900-514 Viana do Castelo",
            telefone = "258822456",
            email = "geral@hvviana.pt",
            site = "https://www.hvviana.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Clínica Veterinária do Lima",
            descricao = "Clínica veterinária",
            localizacao = "Ponte de Lima",
            curso = "Enfermagem Veterinária",
            morada = "Rua Conde de Bertiandos, 4990-078 Ponte de Lima",
            telefone = "258941234",
            email = "info@vetlima.pt",
            site = "https://www.vetlima.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.7667,
            longitude = -8.5833
        ),
        Empresa(
            nome = "Centro Veterinário de Barcelos",
            descricao = "Centro veterinário",
            localizacao = "Barcelos",
            curso = "Enfermagem Veterinária",
            morada = "Avenida dos Combatentes, 4750-279 Barcelos",
            telefone = "253812345",
            email = "geral@vetbarcelos.pt",
            site = "https://www.vetbarcelos.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.5389,
            longitude = -8.6155
        ),
        Empresa(
            nome = "OneVet Group",
            descricao = "Grupo hospitalar veterinário",
            localizacao = "Porto",
            curso = "Enfermagem Veterinária",
            morada = "Rua Augusto Lessa 45, 4200-098 Porto",
            telefone = "225024600",
            email = "careers@onevetgroup.pt",
            site = "https://www.onevetgroup.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "VetNorte",
            descricao = "Hospital veterinário",
            localizacao = "Braga",
            curso = "Enfermagem Veterinária",
            morada = "Rua Nova de Santa Cruz 135, 4710-409 Braga",
            telefone = "253123987",
            email = "rh@vetnorte.pt",
            site = "https://www.vetnorte.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.5503,
            longitude = -8.4289
        ),
        // Engenharia do Ambiente
        Empresa(
            nome = "Águas do Norte",
            descricao = "Gestão de águas e resíduos",
            localizacao = "Vila Real",
            curso = "Engenharia do Ambiente",
            morada = "Rua Dom Pedro de Castro 1A, 5000-669 Vila Real",
            telefone = "259309370",
            email = "geral@adnorte.pt",
            site = "https://www.adnorte.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.3002,
            longitude = -7.7398
        ),
        Empresa(
            nome = "LIPOR",
            descricao = "Gestão de resíduos",
            localizacao = "Porto",
            curso = "Engenharia do Ambiente",
            morada = "Rua da Morena 805, 4435-996 Baguim do Monte",
            telefone = "229770100",
            email = "recursos.humanos@lipor.pt",
            site = "https://www.lipor.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1891,
            longitude = -8.5505
        ),
        Empresa(
            nome = "Resulima",
            descricao = "Tratamento de resíduos",
            localizacao = "Viana do Castelo",
            curso = "Engenharia do Ambiente",
            morada = "Aterro Sanitário do Vale do Lima e Baixo Cávado, 4935-604 Vila Fria",
            telefone = "258240130",
            email = "geral@resulima.pt",
            site = "https://www.resulima.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "EDP Renováveis",
            descricao = "Energia renovável",
            localizacao = "Porto",
            curso = "Engenharia do Ambiente",
            morada = "Avenida 24 de Julho 12A, 1249-300 Porto",
            telefone = "210012500",
            email = "careers@edpr.com",
            site = "https://www.edpr.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Agência Portuguesa do Ambiente",
            descricao = "Entidade governamental",
            localizacao = "Porto",
            curso = "Engenharia do Ambiente",
            morada = "Rua da Murgueira 9, 2610-124 Porto",
            telefone = "214728200",
            email = "geral@apambiente.pt",
            site = "https://www.apambiente.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        // Gestão
        Empresa(
            nome = "Deloitte",
            descricao = "Consultoria empresarial",
            localizacao = "Porto",
            curso = "Gestão",
            morada = "Av. da Boavista 1837, 4100-133 Porto",
            telefone = "225439100",
            email = "ptrecruitment@deloitte.pt",
            site = "https://www.deloitte.com",
            vagasDisponiveis = 5,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Banco BPI",
            descricao = "Instituição financeira",
            localizacao = "Porto",
            curso = "Gestão",
            morada = "Rua Tenente Valadim 284, 4100-476 Porto",
            telefone = "226073100",
            email = "recursos.humanos@bancobpi.pt",
            site = "https://www.bancobpi.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Millennium BCP",
            descricao = "Instituição bancária",
            localizacao = "Porto",
            curso = "Gestão",
            morada = "Praça D. João I 28, 4000-295 Porto",
            telefone = "220040000",
            email = "careers@millenniumbcp.pt",
            site = "https://www.millenniumbcp.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1489,
            longitude = -8.6107
        ),
        Empresa(
            nome = "Sonae MC",
            descricao = "Grupo empresarial",
            localizacao = "Matosinhos",
            curso = "Gestão",
            morada = "Rua João Mendonça 529, 4464-501 Senhora da Hora",
            telefone = "229561000",
            email = "careers@sonaemc.com",
            site = "https://www.sonaemc.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1812,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Jerónimo Martins",
            descricao = "Grupo empresarial",
            localizacao = "Lisboa",
            curso = "Gestão",
            morada = "Rua Actor António Silva 7, 1649-033 Lisboa",
            telefone = "217532000",
            email = "recursos.humanos@jeronimo-martins.pt",
            site = "https://www.jeronimo-martins.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 38.7223,
            longitude = -9.1393
        ),

        // Biotecnologia (adicionando mais empresas)
        Empresa(
            nome = "Bial",
            descricao = "Indústria farmacêutica",
            localizacao = "Trofa",
            curso = "Biotecnologia",
            morada = "À Av. da Siderurgia Nacional, 4745-457 Coronado",
            telefone = "229866100",
            email = "rh@bial.com",
            site = "https://www.bial.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.2833,
            longitude = -8.5833
        ),
        Empresa(
            nome = "Hovione",
            descricao = "Indústria farmacêutica",
            localizacao = "Loures",
            curso = "Biotecnologia",
            morada = "Sete Casas, 2674-506 Loures",
            telefone = "219847000",
            email = "careers@hovione.com",
            site = "https://www.hovione.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 38.8283,
            longitude = -9.1747
        ),
        Empresa(
            nome = "Bluepharma",
            descricao = "Indústria farmacêutica",
            localizacao = "Coimbra",
            curso = "Biotecnologia",
            morada = "São Martinho do Bispo, 3045-016 Coimbra",
            telefone = "239800300",
            email = "rh@bluepharma.pt",
            site = "https://www.bluepharma.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 40.2033,
            longitude = -8.4103
        ),
        Empresa(
            nome = "GenIbet",
            descricao = "Biotecnologia e investigação",
            localizacao = "Oeiras",
            curso = "Biotecnologia",
            morada = "Quinta do Marquês, 2784-505 Oeiras",
            telefone = "214469100",
            email = "careers@genibet.pt",
            site = "https://www.genibet.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 38.6972,
            longitude = -9.3177
        ),
        Empresa(
            nome = "Novartis",
            descricao = "Indústria farmacêutica",
            localizacao = "Porto",
            curso = "Biotecnologia",
            morada = "Avenida Professor Doutor Aníbal Cavaco Silva 2, 2740-255 Porto Salvo",
            telefone = "210608000",
            email = "recrutamento.portugal@novartis.com",
            site = "https://www.novartis.com",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),

        // Engenharia Alimentar
        Empresa(
            nome = "Nestlé Portugal",
            descricao = "Indústria alimentar",
            localizacao = "Porto",
            curso = "Engenharia Alimentar",
            morada = "Rua Alexandre Herculano 8, 2799-554 Linda-a-Velha",
            telefone = "214147500",
            email = "careers@pt.nestle.com",
            site = "https://www.nestle.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Lactogal",
            descricao = "Indústria de laticínios",
            localizacao = "Porto",
            curso = "Engenharia Alimentar",
            morada = "Rua do Freixo 1169, 4300-219 Porto",
            telefone = "225391700",
            email = "rh@lactogal.pt",
            site = "https://www.lactogal.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1489,
            longitude = -8.5891
        ),
        Empresa(
            nome = "Unicer",
            descricao = "Indústria de bebidas",
            localizacao = "Porto",
            curso = "Engenharia Alimentar",
            morada = "Via Norte, 4465-764 Leça do Balio",
            telefone = "229052100",
            email = "recursos.humanos@unicer.pt",
            site = "https://www.unicer.pt",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.2000,
            longitude = -8.6333
        ),
        Empresa(
            nome = "Frulact",
            descricao = "Indústria alimentar",
            localizacao = "Maia",
            curso = "Engenharia Alimentar",
            morada = "Rua do Outeiro 589, 4475-150 Gemunde",
            telefone = "229749200",
            email = "careers@frulact.pt",
            site = "https://www.frulact.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.2500,
            longitude = -8.6167
        ),
        Empresa(
            nome = "Sumol+Compal",
            descricao = "Indústria de bebidas",
            localizacao = "Porto",
            curso = "Engenharia Alimentar",
            morada = "Estrada Nacional 250, 2665-191 Carnaxide",
            telefone = "214241600",
            email = "recrutamento@sumolcompal.pt",
            site = "https://www.sumolcompal.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),

        // Engenharia da Computação Gráfica e Multimédia
        Empresa(
            nome = "Blizzard",
            descricao = "Desenvolvimento de jogos",
            localizacao = "Porto",
            curso = "Engenharia da Computação Gráfica e Multimédia",
            morada = "Rua da Lionesa 446, 4465-671 Leça do Balio",
            telefone = "229969700",
            email = "careers@blizzard.com",
            site = "https://www.blizzard.com",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.2000,
            longitude = -8.6333
        ),
        Empresa(
            nome = "Pixelmatters",
            descricao = "Design e desenvolvimento digital",
            localizacao = "Porto",
            curso = "Engenharia da Computação Gráfica e Multimédia",
            morada = "Rua Sá da Bandeira 651, 4000-437 Porto",
            telefone = "220101510",
            email = "hello@pixelmatters.com",
            site = "https://www.pixelmatters.com",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1489,
            longitude = -8.6107
        ),
        Empresa(
            nome = "Fabamaq",
            descricao = "Desenvolvimento de jogos",
            localizacao = "Porto",
            curso = "Engenharia da Computação Gráfica e Multimédia",
            morada = "Rua do Heroísmo 333, 4300-096 Porto",
            telefone = "225898989",
            email = "hr@fabamaq.com",
            site = "https://www.fabamaq.com",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 41.1489,
            longitude = -8.5891
        ),
        Empresa(
            nome = "Sword Health",
            descricao = "Tecnologia de saúde digital",
            localizacao = "Porto",
            curso = "Engenharia da Computação Gráfica e Multimédia",
            morada = "Rua Sá da Bandeira 651, 4000-437 Porto",
            telefone = "220107510",
            email = "careers@swordhealth.com",
            site = "https://www.swordhealth.com",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.1489,
            longitude = -8.6107
        ),
        Empresa(
            nome = "Xpand IT",
            descricao = "Consultoria tecnológica",
            localizacao = "Porto",
            curso = "Engenharia da Computação Gráfica e Multimédia",
            morada = "Rua do Rosário 174, 4050-521 Porto",
            telefone = "222073910",
            email = "recruitment@xpand-it.com",
            site = "https://www.xpand-it.com",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1489,
            longitude = -8.6107
        ),

        // Engenharia Eletrónica e Redes de Computadores
        Empresa(
            nome = "Altice Labs",
            descricao = "Telecomunicações e redes",
            localizacao = "Aveiro",
            curso = "Engenharia Eletrónica e Redes de Computadores",
            morada = "Rua Eng. José Ferreira Pinto Basto, 3810-106 Aveiro",
            telefone = "234403200",
            email = "contact@alticelabs.com",
            site = "https://www.alticelabs.com",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 40.6333,
            longitude = -8.6500
        ),
        Empresa(
            nome = "Cisco Portugal",
            descricao = "Redes e telecomunicações",
            localizacao = "Porto",
            curso = "Engenharia Eletrónica e Redes de Computadores",
            morada = "Av. Dom João II, 1990-084 Lisboa",
            telefone = "214124000",
            email = "careers@cisco.pt",
            site = "https://www.cisco.com",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),
        Empresa(
            nome = "Nokia Solutions",
            descricao = "Telecomunicaçes",
            localizacao = "Lisboa",
            curso = "Engenharia Eletrónica e Redes de Computadores",
            morada = "Av. do Forte 6, 2790-072 Carnaxide",
            telefone = "214251000",
            email = "recruitment.portugal@nokia.com",
            site = "https://www.nokia.com",
            vagasDisponiveis = 5,
            vagasOcupadas = 0,
            latitude = 38.7223,
            longitude = -9.1393
        ),
        Empresa(
            nome = "Huawei Portugal",
            descricao = "Tecnologia e telecomunicações",
            localizacao = "Lisboa",
            curso = "Engenharia Eletrónica e Redes de Computadores",
            morada = "Av. Dom João II 51B, 1990-085 Lisboa",
            telefone = "214124100",
            email = "recruitment.pt@huawei.com",
            site = "https://www.huawei.com",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 38.7223,
            longitude = -9.1393
        ),
        Empresa(
            nome = "NOS",
            descricao = "Telecomunicações",
            localizacao = "Porto",
            curso = "Engenharia Eletrónica e Redes de Computadores",
            morada = "Rua Ator António Silva 9, 1600-404 Lisboa",
            telefone = "217824700",
            email = "recrutamento@nos.pt",
            site = "https://www.nos.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.1579,
            longitude = -8.6291
        ),

        // Educação Social Gerontológica (completando até 5 empresas)
        Empresa(
            nome = "Centro Social e Cultural de Vila Praia de Âncora",
            descricao = "Centro social",
            localizacao = "Vila Praia de Âncora",
            curso = "Educação Social Gerontológica",
            morada = "Rua 5 de Outubro, 4910-456 Vila Praia de Âncora",
            telefone = "258911789",
            email = "geral@csccvpa.pt",
            site = "https://www.csccvpa.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 3,
            latitude = 41.8186,
            longitude = -8.8586
        ),
        Empresa(
            nome = "Lar de São José",
            descricao = "Lar de idosos",
            localizacao = "Viana do Castelo",
            curso = "Educação Social Gerontológica",
            morada = "Rua de São José, 4900-012 Viana do Castelo",
            telefone = "258822345",
            email = "geral@larsaojose.pt",
            site = "https://www.larsaojose.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Centro Social da Paróquia de Areosa",
            descricao = "Centro social",
            localizacao = "Viana do Castelo",
            curso = "Educação Social Gerontológica",
            morada = "Rua da Igreja, 4900-878 Areosa",
            telefone = "258835125",
            email = "geral@csareosa.pt",
            site = "https://www.csareosa.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.7052,
            longitude = -8.8520
        ),

        // Arte e Design (completando até 5 empresas)
        Empresa(
            nome = "Galeria Zet",
            descricao = "Galeria de arte",
            localizacao = "Viana do Castelo",
            curso = "Arte e Design",
            morada = "Rua Manuel Espregueira 140, 4900-318 Viana do Castelo",
            telefone = "258822111",
            email = "info@galeriazet.pt",
            site = "https://www.galeriazet.pt",
            vagasDisponiveis = 2,
            vagasOcupadas = 1,
            latitude = 41.6946,
            longitude = -8.8362
        ),
        Empresa(
            nome = "Atelier Design Factory",
            descricao = "Estúdio de design",
            localizacao = "Braga",
            curso = "Arte e Design",
            morada = "Rua do Raio 300, 4710-922 Braga",
            telefone = "253123789",
            email = "jobs@designfactory.pt",
            site = "https://www.designfactory.pt",
            vagasDisponiveis = 3,
            vagasOcupadas = 2,
            latitude = 41.5503,
            longitude = -8.4289
        ),
        Empresa(
            nome = "Creative Hub Porto",
            descricao = "Espaço criativo",
            localizacao = "Porto",
            curso = "Arte e Design",
            morada = "Rua das Flores 150, 4050-262 Porto",
            telefone = "220123789",
            email = "info@creativehub.pt",
            site = "https://www.creativehub.pt",
            vagasDisponiveis = 4,
            vagasOcupadas = 1,
            latitude = 41.1579,
            longitude = -8.6291
        )
    )
} 